courses/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from courses.views import HomeView,AboutView,ContactView,CourseListView, CourseDetailView,LessonDetailView, SearchView, create_cat, create_course, create_lesson,PostListView,PostDetailView, create_post, delete_post,Profile, teacherReq

app_name = 'courses'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('courses/<int:category>', CourseListView, name='course_list'),
    path('courses/<slug>/', login_required(CourseDetailView.as_view()), name='course_detail'),
    path('courses/<course_slug>/<lesson_slug>/', login_required(LessonDetailView.as_view()), name='lesson_detail'),
    path('search/', SearchView, name='search_result'),
    path('create/category', create_cat, name='create_cat'),
    path('create/course', create_course, name='create_course'),
    path('create/lesson', create_lesson, name='create_lesson'),
    path('profile/', Profile, name='profile'),
    path('request/', teacherReq, name='teacherReq'),
    path('blog/',PostListView.as_view(),name='post_list'),
    path('blog/<int:pk>/',PostDetailView.as_view(),name='post_detail'),
    path('blog/create/', create_post, name='create_post'),
    path('blog/<int:id>/delete', delete_post, name='delete_post')


]

knowledge/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import  handler404, handler403, handler500


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('courses.urls',namespace='courses')),
    path('accounts/', include('allauth.urls')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

courses/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone
from PIL import Image
# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    bio = models.CharField(max_length=200, blank=True, null=True,default=' ')
    profile_pic = models.ImageField(default='default.png', upload_to = 'profile_pics')
    is_teacher = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username + ' Profile'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.profile_pic.path)
        if img.height >100 or img.width>100:
            output_size = (200,200)
            img.thumbnail(output_size)
            img.save(self.profile_pic.path)


class teacherReq(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=254)
    number = models.CharField(max_length=15)


    def __str__(self):
        return self.profile.user.username


class category(models.Model):
    title = models.CharField(max_length=150)
    description = models.TextField(max_length= 200, null=True)
    image = models.ImageField(upload_to='cat_images', default='cat_images/default.jpg')

    def __str__(self):
        return '{}'.format(self.title)

class course(models.Model):
    creator = models.ForeignKey(User,on_delete = models.CASCADE)
    slug = models.SlugField()
    title = models.CharField(max_length=30)
    category = models.ForeignKey(category,on_delete=models.CASCADE)
    description = models.TextField(max_length=400)
    create_date = models.DateTimeField(auto_now=True)
    price = models.IntegerField()
    image = models.ImageField(upload_to='course_images', default='default.jpg')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("courses:course_detail", kwargs={"slug": self.slug})

    @property
    def lessons(self):
        return self.lesson_set.all().order_by('position')



class Lesson(models.Model):
    slug = models.SlugField()
    title = models.CharField(max_length=30)
    course = models.ForeignKey(course,on_delete=models.CASCADE)
    video_id = models.CharField(max_length=11)
    position = models.IntegerField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("courses:lesson_detail", kwargs={"course_slug": self.course.slug,'lesson_slug':self.slug})


class Post(models.Model):
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    title = models.CharField(max_length=30)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)

    def get_absolute_url(self):
        return reverse("courses:blog_detail", kwargs={"pk": self.pk})

    def __str__(self):
        return self.title

courses/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import category, course, Lesson,Post,Profile



class categoryForm(forms.ModelForm):
    class Meta:
        model = category
        fields = '__all__'

class courseForm(forms.ModelForm):
    class Meta:
        model = course
        fields = ['creator','slug', 'title', 'category', 'description','price','image']
        labels = {
            'title':'Course Title'
        }
        widgets = {'creator': forms.HiddenInput(), 'slug': forms.HiddenInput()}


class LessonForm(forms.ModelForm):
    class Meta:
        model = Lesson
        fields = ['slug','title', 'course', 'video_id', 'position', ]
        widgets = {
            'slug': forms.HiddenInput()
        }

class PostForm(forms.ModelForm):

    class Meta:
        model= Post
        fields = ('title','text')

    def save_form(self, request, instance, form, change):
        user = request.user
        instance = form.save(commit=False)
        if not change or not instance.author:
            instance.author = user
        instance.modified_by = user
        instance.save()
        form.save_m2m()
        return instance

class userUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username','email']


class profileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields =['bio','profile_pic']

courses/views.py
import secrets
from django.shortcuts import render, redirect
from django.views.generic import TemplateView,ListView,DetailView,View,CreateView,UpdateView,DeleteView
from courses.models import category,Lesson,course,teacherReq,Post
from django.shortcuts import render, get_object_or_404,redirect
from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import categoryForm, courseForm, LessonForm,profileUpdateForm, userUpdateForm, PostForm
from django.utils import timezone
from django.urls import reverse_lazy
from courses.models import Profile as Pro
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.core.mail import EmailMessage
# Create your views here.


class HomeView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cat = category.objects.all()
        context['category'] = cat
        return context

class AboutView(TemplateView):
    template_name = 'about.html'


class ContactView(TemplateView):
    template_name = 'contact.html'



def CourseListView(request, category):
    courses = course.objects.filter(category=category)
    context = {
        'courses':courses
    }
    return render(request, 'courses/course_list.html', context)



class CourseDetailView(DetailView):
    context_object_name = 'course'
    template_name = 'courses/course_detail.html'
    model = course



class LessonDetailView(View,LoginRequiredMixin):
    def get(self, request, course_slug, lesson_slug, *args, **kwargs):
        course = get_object_or_404(course, slug=course_slug)
        lesson = get_object_or_404(Lesson, slug=lesson_slug)
        context = {'lesson': lesson}
        return render(request, "courses/lesson_detail.html", context)


@login_required
def SearchView(request):
    if request.method == 'POST':
        sWord = request.POST.get('search')
        results = Lesson.objects.filter(title__contains=sWord)
        context = {
            'results':results
        }
        return render(request, 'courses/search_result.html', context)


@login_required
def create_cat(request):
    if not request.user.profile.is_teacher == True:
        messages.error(request, f'You do not have teacher access')
        return redirect('courses:home')
    if request.method == 'POST':
        form = categoryForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, f'Category Created')
            return redirect('courses:home')
    else:
        form = categoryForm()
    context = {
        'form':form
    }
    return render(request, 'courses/create_cat.html', context)


@login_required
def create_course(request):
    if not request.user.profile.is_teacher == True:
        messages.error(request, f'You do not have teacher access')
        return redirect('courses:home')
    if request.method == 'POST':
        form = courseForm(request.POST)
        if form.is_valid():
            form.save()
            category = form.cleaned_data['category']
            slug = category.id
            messages.success(request, f'Course Created')
            return redirect('/courses/' + str(slug))
    else:
        form = courseForm(initial={'creator':request.user.id, 'slug':secrets.token_hex(nbytes=16)})
    context = {
        'form':form
    }
    return render(request, 'courses/create_course.html', context)


@login_required
def create_lesson(request):
    if not request.user.profile.is_teacher == True:
        messages.error(request, f'You do not have teacher access')
        return redirect('courses:home')
    if request.method == 'POST':
        form = LessonForm(request.POST)
        if form.is_valid():
            form.save()
            course = form.cleaned_data['course']
            slug = lesson.slug
            messages.success(request, f'Lesson Created')
            return redirect('/courses/' + str(slug) )
    else:
        form = LessonForm(initial={'slug':secrets.token_hex(nbytes=16)})
    context = {
        'form':form
    }
    return render(request, 'courses/create_lesson.html', context)


def view_404(request, exception):
    return render(request, '404.html')

def view_403(request, exception):
    return render(request, '403.html')

def view_500(request):
    return render(request, '500.html')


@login_required
def Profile(request):
    if request.method == 'POST':
        u_form = userUpdateForm(request.POST,instance=request.user)
        p_form = profileUpdateForm(request.POST,request.FILES,instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, 'Your account has been successfully updated!')
            return redirect('courses:profile')
    else:
        u_form = userUpdateForm(instance=request.user)
        p_form = profileUpdateForm(instance=request.user.profile)

    context= {
        'u_form':u_form,
        'p_form':p_form
    }
    return render(request,'profile/profile.html',context)

@login_required
def teacherReq(request):
    if request.method == 'POST':
        u= request.user
        b= ""
        cprofile = Profile(instance= request,user=u,bio=b)
        cprofile.save()
        tname = request.POST.get('name')
        temail = request.POST.get('e-mail')
        tnumber = request.POST.get('phone')
        prof = request.user.profile
        treq = teacherReq(profile=prof, name=tname, email=temail, number=tnumber)
        treq.save()
        prof_id = prof.id
        Pro.objects.filter(id=prof_id).update(is_teacher=True)

        message = 'Your request for a teacher account has been accepted! Now you can go back to Knowledge and upload courses and lectures. Good Luck!'
        send_mail(
            'The request was accepted.',
            message,
            'knowledge@no-reply.com',
            [email],
            fail_silently=False,
        )
        send_mail(
            'Knowledge',
            'Someone applied for a teacher account. Me info: ' + tname + ' , ' + temail + ' , ' + tnumber + ' , ' + str(prof) + '.',
            'knowledge@no-reply.com',
            ['hridita1998@gmail.com'],
            fail_silently=False,
        )
        messages.info(request, f'The request was sent successfully, you will be notified by email.')
        return redirect('courses:home')



class PostListView(ListView):
    context_object_name = 'posts'
    template_name = 'blog/post_list.html'
    ordering = ['-created_date']
    model = Post



class PostDetailView(DetailView):
    context_object_name = 'post'
    template_name = 'blog/post_detail.html'
    model = Post

@login_required
def create_post(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        text = request.POST.get('text')
        postim = Post(title=title, text=text, author=request.user)
        postim.save()
        messages.success(request, f'Post created successfully.')
        return redirect('courses:post_list')
    return render(request, 'blog/create_post.html')
    
@login_required
def delete_post(request, id):
    Post(id = id).delete()
    return redirect('courses:post_list')

courses/templates/blog/create_post.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <div class="text-center">
        <h1>Create Post</h1>
    </div>
    <form method="post" action="blog/create/">
        {% csrf_token %}
        <label for="">Title*</label>
        <input type="text" class="form-control" name="title" placeholder="Title of the post">
        <label for="">Text*</label>
        <textarea class="form-control" name="text" id="" cols="30" rows="10" placeholder="Content"></textarea>
        <br>
        <button class="site-btn">Create</button>
    </form>

</div>
<br>
{% endblock %}

courses/templates/blog/post_detail.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

<div class="container">
    <div class="row">
      <div class="col-lg-9">
          <h1>Post Details:</h1>
        <!-- blog post -->
        <div class="blog-post">
          <img src="img/blog/1.jpg" alt="">
          <h3>{{ post.title }}</h3>
          <div class="blog-metas">
            <div class="blog-meta author">
              <div class="post-author set-bg" data-setbg="/media/{{ post.author.profile.profile_pic }}"></div>
              <a href="#">{{ post.author|capfirst }}</a>
            </div>
            <div class="blog-meta">
              <a href="#">{{ post.created_date }}</a>
            </div>
          </div>
          <p>{{ post.text|capfirst }} </p>
          <a href="/blog/" class="btn btn-dark">Return</a>
          {% if post.author == request.user %}
          <a href="/blog/{{ post.id }}/delete" class="btn btn-danger">Delete Post</a>
          {% endif %}
        </div>
      </div>
    </div>
</div>

{% endblock content %}

courses/templates/blog/post_list.html
{% extends 'base.html' %}
{% load static %}


{% block content %}



<!-- Page  -->
<section class="blog-page spad pb-0">
  <div class="container">
    <div class="row">
      <div class="col-lg-9">

        <a href="{% url 'courses:create_post' %}" style="color: white;" class="site-btn">Create a post</a>
        {% if posts %}
        {% for post in posts %}
        <!-- blog post -->
        <div class="blog-post">
          <img src="img/blog/1.jpg" alt="">
          <h3>{{ post.title }}</h3>
          <div class="blog-metas">
            <div class="blog-meta author">
              <div class="post-author set-bg" data-setbg="/media/{{ post.author.profile.profile_pic }}"></div>
              <a href="#">{{ post.author|capfirst }}</a>
            </div>
            <div class="blog-meta">
              <a href="#">{{ post.created_date }}</a>
            </div>
          </div>
          <p>{{ post.text|capfirst }} </p>
          <a href="/blog/{{ post.id }}" class="btn btn-primary">Read More</a>
        </div>
        {% endfor %}
        {% else %}


        {% endif %}


      </div>
      <div class="col-lg-3 col-md-5 col-sm-9 sidebar">
        <div class="sb-widget-item">
          <form class="search-widget">
            <input type="text" placeholder="Kerko">
            <button><i class="fa fa-search"></i></button>
          </form>
        </div>
        <div class="sb-widget-item">
          <h4 class="sb-w-title">Classrooms</h4>
          <ul>
            <li><a href="#">Program</a></li>
            <li><a href="#">Social networks</a></li>
            <li><a href="#">News</a></li>
            <li><a href="#">Event</a></li>
          </ul>
        </div>
        <div class="sb-widget-item">
          <h4 class="sb-w-title">Archive</h4>
          <ul>
            <li><a href="#">December 2020</a></li>
            <li><a href="#">January 2021</a></li>
            <li><a href="#">February 2021</a></li>
            <li><a href="#">March 2021</a></li>
            <li><a href="#">April 2021</a></li>
          </ul>
        </div>
        <div class="sb-widget-item">
          <h4 class="sb-w-title">Hashtags</h4>
          <div class="tags">
            <a href="#">education</a>
            <a href="#">courses</a>
            <a href="#">development</a>
            <a href="#">design</a>
            <a href="#">on line courses</a>
            <a href="#">wp</a>
            <a href="#">html5</a>
            <a href="#">music</a>
          </div>
        </div>
        <div class="sb-widget-item">
          <div class="add">
            <a href="#"><img src="img/add.jpg" alt=""></a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Page end -->

{% endblock content %}